# Generated by Django 4.2.1 on 2023-07-11 17:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_donation'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
